version: '3'
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app
    restart: always
    environment:
      DB_HOST: postgresql
    ports:
      - "5000:5000"
    depends_on:
      - postgresql
    networks:
      - backend

  postgresql:
    image: postgres:13.14
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_DB: cloudscraper
      POSTGRES_USER: cloudscraper
      POSTGRES_PASSWORD: xswCdeMht
    ports:
      - "5432:5432"
    volumes:
      - /tmp/postgresqldata:/var/lib/postgresql/data
      - ./connection/DatabaseQuery.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgresqldata:
    driver: local

