#FROM 204184355380.dkr.ecr.ap-south-1.amazonaws.com/non-prod-ttn-sws-base-image:fluentbit-1.4-debug
FROM fluent/fluent-bit:latest
#COPY fluent.conf /fluent-bit/etc/fluent-bit.conf
COPY parsers.conf /fluent-bit/etc/parsers.conf
