apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: fluent-bit
    namespace: qa
    labels:
        app: fluent-bit
spec:
    selector:
        matchLabels:
            app: fluent-bit
    template:
        metadata:
            labels:
                app: fluent-bit
        spec:
            containers:
                -   name: fluent-bit
                    image: "204184355380.dkr.ecr.ap-south-1.amazonaws.com/non-prod-ttn-sws-new-base-setup:fluent-bit-multiarch"
                    imagePullPolicy: Always
                    resources:
                        limits:
                            memory: 1024Mi
                            cpu: 400m
                        requests:
                            memory: 1024Mi
                            cpu: 400m
                    volumeMounts:
                        -   name: app-logs
                            mountPath: /opt/logs
                        -   name: varlog
                            mountPath: /opt/pod
                        -   name: varlibdockercontainers
                            mountPath: /var/lib/docker/containers
                    env:
                        -   name: ENV
                            value: "qa"
                        -   name: FLUENT_ELASTIC_SEARCH_HOST
                            value: "10.25.64.24"
                        -   name: FLUENT_ELASTIC_SEARCH_PORT
                            value: "9200"
            priorityClassName: system-node-critical
            terminationGracePeriodSeconds: 30
            nodeSelector:
                ENV: qa
            tolerations:
            - key: "platform"
              operator: "Equal"
              value: "amd"
              effect: "NoSchedule"
            - key: "platform"
              operator: "Equal"
              value: "arm"
              effect: "NoSchedule"
            volumes:
                -   name: varlibdockercontainers
                    hostPath:
                        path: /var/lib/docker/containers
                -   name: varlog
                    hostPath:
                        path: /var/log/pods
                -   name: app-logs
                    hostPath:
                        path: /opt/logs
